### ISSUE TITLE
Please pin mpfr.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/r-rmpfr-feedstock#1]
Next version update 4.0.0 is incompatible with 3.*

**Comment by bgruening** [comment]
@isuruf does it break ABI or API? mpfr is only a runtime dependency here, so it should be fine if only ABI is broken.

**Comment by isuruf** [comment]
ABI only I think. It's a build dependency here (Pulled in by gcc) and links to `libmpfr.4.dylib` which will be unavailable in mpfr-4.0.0 (libmpfr.6.dylib)

**Comment by bgruening** [comment]
Ok, thanks for the explanation.
See here: https://github.com/conda-forge/r-rmpfr-feedstock/pull/2
